name: pgmini-printsvc
version: git
summary: PG Mini Print Service for print accounting and administration by user
description: |
 This is a basic webapp packaged in Apache Tomcat utilising the Spring Framework and PostgreSQL.
grade: devel
confinement: strict

parts:
 my-part:
  plugin: dump
  install:
   cp -r ../out/artifacts/printsvc_war_exploded/* ./webapps/ROOT/
  after: [tomcat]

apps:
 tomcat:
  command: tomcat-launch
  daemon: simple
  plugs: [netowrk-bind]
